apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react
  template:
    metadata:
      labels:
        app: client-react
    spec:
      containers:
      - name: client-react
        image: adhiana46/ms-node-client-react
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
