apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: adhiana46/ms-node-query-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
